// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DescriptionInput: typeof import('./src/components/exercise-form/description-input/DescriptionInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ExerciseCard: typeof import('./src/components/exercise-list/exercise-card/ExerciseCard.vue')['default']
    ExerciseForm: typeof import('./src/components/exercise-form/ExerciseForm.vue')['default']
    ExerciseList: typeof import('./src/components/exercise-list/ExerciseList.vue')['default']
    LinkInput: typeof import('./src/components/exercise-form/link-input/LinkInput.vue')['default']
    NameInput: typeof import('./src/components/exercise-form/name-input/NameInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitButton: typeof import('./src/components/exercise-form/submit-button/SubmitButton.vue')['default']
  }
}
