// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DescriptionInput: typeof import('./src/components/exercise-form/description-input/DescriptionInput.vue')['default']
    EditButton: typeof import('./src/components/exercise-list/edit-button/EditButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ExerciseCard: typeof import('./src/components/exercise-list/exercise-card/ExerciseCard.vue')['default']
    ExerciseDialog: typeof import('./src/components/exercise-form/ExerciseDialog.vue')['default']
    ExerciseForm: typeof import('./src/components/exercise-form/ExerciseForm.vue')['default']
    ExerciseList: typeof import('./src/components/exercise-list/ExerciseList.vue')['default']
    FormLegend: typeof import('./src/components/exercise-form/form-legend/FormLegend.vue')['default']
    LinkInput: typeof import('./src/components/exercise-form/link-input/LinkInput.vue')['default']
    NameInput: typeof import('./src/components/exercise-form/name-input/NameInput.vue')['default']
    OpenDialog: typeof import('./src/components/exercise-form/OpenDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitButton: typeof import('./src/components/exercise-form/submit-button/SubmitButton.vue')['default']
  }
}
